import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  myPortfolioPage: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    flexWrap: "wrap",
    height: "80vh",
    margin: "0",
    padding: "0",
    overflowY: "auto",
  },
  portfolioFilter: {
    border: "2px solid #000",
    height: "50vh",
    width: "20vw",
    margin: "50px 10px",
    overflow: "none",
    borderRadius: "40px",
    color: "#6f7072",
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    position: "sticky",
    top: "100px",
    backgroundColor: "#e9ecef",
  },
  portfolioAllTransactions: {
    minHeight: "50vh",
    width: "60vw",
    margin: "50px 10px",
  },
  loader: {},
  transactionList: {
    listStyleType: "none",
  },
  eachTransaction: {
    borderBottom: "1px solid #000",
    margin: "5px 0px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  transactionParameters: {
    display: "flex",
    alignItems: "center",
  },
  stockName: {
    display: "flex",
    alignItems: "center",
    margin: "10px 10px",
    padding: "10px 40px",
    width: "30%",
  },
  stockSymbol: {
    display: "flex",
    alignItems: "center",
    margin: "10px 10px",
    padding: "10px 40px",
    width: "15%",
  },
  stockPrice: {
    display: "flex",
    alignItems: "center",
    margin: "10px 10px",
    padding: "10px 40px",
    width: "15%",
  },
  stockTimeStamp: {
    display: "flex",
    alignItems: "center",
    width: "10%",
  },
  statusType: {
    margin: "10px 20px",
    width: "10px",
    height: "10px",
    borderRadius: "50px",
  },
  filterClearAll: {
    width: "100%",
    height: "10%",
    display: "flex",
    flexDirection: "row",
    borderBottom: "2px solid #6f7072",
    alignItems: "center",
    fontSize: "1.2rem",
    color: "#000",
    fontFamily: "Roboto",
  },
  filterSearch: {
    width: "100%",
    height: "10%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderBottom: "2px solid #6f7072",
  },
  filterDate: {
    width: "100%",
    height: "10%",
    display: "flex",
    flexDirection: "row",
    borderBottom: "2px solid #6f7072",
  },
  filterStatus: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    borderBottom: "2px solid #6f7072",
  },
  filterStockNames: {
    width: "95%",
    height: "50%",
    display: "flex",
    flexDirection: "column",
    overflowY: "scroll",
    padding: "5px 5px",
  },
};
